###
POST http://localhost:8080/api/course/getAll
Content-Type: application/json

{
  "token": "{\"account\": \"1234567890\", \"username\": \"吴京\", \"expires_at\": \"2024-05-29T15:10:59\"}.v1BBaaz4+ZUwf2BamdMuVbUlteb+npnkcZOIRXi50/g="
}

###
POST http://localhost:8080/api/course/userGet
Content-Type: application/json

{
  "token": "{\"account\": \"1234567890\", \"username\": \"吴京\", \"expires_at\": \"2024-05-29T15:10:59\"}.v1BBaaz4+ZUwf2BamdMuVbUlteb+npnkcZOIRXi50/g="
}

###
POST http://localhost:7788/api/course/idDelete
Content-Type: application/json

{
  "token": "{\"account\": \"1234567890\", \"id\": \"1245706057990152192\", \"expires_at\": \"2024-05-30T20:33:56\"}.XFx5R0yZAR2xF39G9R16mMnZG4ueXIDhAvSM6j0kpwo=",
  "data": "1245711238811230208"
}