GET http://localhost:8080/api/lib/get

###
POST http://localhost:8080/api/lib/getAll

###
POST http://localhost:8080/api/lib/add
Content-Type: application/json

{
  "token": "{\"account\": \"1234567890\", \"username\": \"吴京\", \"expires_at\": \"2024-05-29T10:10:41\"}.yRBYNxqy8scr5UNqnKvb5uXThpgUZyQzQbn3NkEAyUM=",
  "data": {
    "id": null,
    "name": "811",
    "type": "猪猪实验室 "
  }
}

###
POST http://localhost:8080/api/lib/change
Content-Type: application/json

{
  "token": "{\"account\": \"1234567890\", \"username\": \"吴京\", \"expires_at\": \"2024-05-29T10:10:41\"}.yRBYNxqy8scr5UNqnKvb5uXThpgUZyQzQbn3NkEAyUM=",
  "data": {
    "id": "1245205265055096832",
    "name": "811",
    "type": "计算机实验室 "
  }
}

###
POST http://localhost:8080/api/lib/typeGet

计算机实验室

###
POST http://localhost:8080/api/lib/idDelete
Content-Type: application/json

1244637752521007104