###
POST http://localhost:8080/api/occupation/add
Content-Type: application/json

{
  "token": "{\"account\": \"1234567890\", \"id\": \"1244574091173335040\", \"expires_at\": \"2024-05-30T15:24:38\"}.FWiK9lZ0hkeq3jRNBNSXqnSEktyQT3Nmhg7yLnNPdKc=",
  "data": {
    "id": null,
    "libId": "1244944171988295680",
    "courseId": "1245273007166726144",
    "libName": "",
    "courseName": "小猪蹦迪",
    "week": [
      1,
      10
    ],
    "day": 3,
    "time": [
      1,
      4
    ]
  }
}